version: "3"

services:
  mysql-go:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_project
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
