# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Create env file
        run: |
          touch .env
          echo POSTGRES_USER=${POSTGRES_USER} >> .env
          echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
          echo "DB_ROOT_PASSWORD=$GO_PROJECT_DB_ROOT_PASSWORD" >> $GITHUB_ENV   
          echo "DB_DATABASE=$GO_PROJECT_DB_DATABASE" >> $GITHUB_ENV   
          echo "DB_USERNAME=$GO_PROJECT_DB_USERNAME" >> $GITHUB_ENV   
          echo "DB_PASSWORD=$GO_PROJECT_DB_PASSWORD" >> $GITHUB_ENV   
          echo "DB_HOST=$GO_PROJECT_DB_HOST" >> $GITHUB_ENV   
          echo "DB_PORT=$GO_PROJECT_DB_PORT" >> $GITHUB_ENV   
          echo "JTW_SECRET_KEY=$GO_PROJECT_JTW_SECRET_KEY" >> $GITHUB_ENV   
          echo "JTW_EXPIRATION_TIME=$GO_PROJECT_JTW_EXPIRATION_TIME" >> $GITHUB_ENV   
          echo "JTW_REFRESH_SECRET_KEY=$GO_PROJECT_JTW_REFRESH_SECRET_KEY" >> $GITHUB_ENV   
          echo "JTW_REFRESH_EXPIRATION_TIME=$GO_PROJECT_JTW_REFRESH_EXPIRATION_TIME" >> $GITHUB_ENV   
          cat .env
      - name: Install dependencies
        run: |
          docker-compose -f docker/docker-compose.yml up -d
